### ISSUE TITLE
App breaks when I press the = button again after successfully performing a calculation

### ISSUE THREAD

**Issue by ancode4** [niketajn/calculator-app#1]
Here is the error stack trace I see on the screen:

Uncaught runtime errors:
×
ERROR
inputVal.includes is not a function
TypeError: inputVal.includes is not a function
    at http://localhost:3000/static/js/bundle.js:33:20
    at Array.filter (<anonymous>)
    at calculate (http://localhost:3000/static/js/bundle.js:32:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:9805:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:9849:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:9906:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:9920:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:14064:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:14090:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:14101:9)
ERROR
inputVal.includes is not a function
TypeError: inputVal.includes is not a function
    at http://localhost:3000/static/js/bundle.js:33:20
    at Array.filter (<anonymous>)
    at calculate (http://localhost:3000/static/js/bundle.js:32:16)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:9805:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:9849:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:9906:35)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/static/js/bundle.js:9920:29)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:14064:7)
    at processDispatchQueueItemsInOrder (http://localhost:3000/static/js/bundle.js:14090:11)
    at processDispatchQueue (http://localhost:3000/static/js/bundle.js:14101:9)

**Comment by niketajn** [comment]
It is resolved
